// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Project_SWP391.Data;

#nullable disable

namespace Project_SWP391.Migrations
{
    [DbContext(typeof(ApplicationDBContext))]
    [Migration("20240920122614_DBInit")]
    partial class DBInit
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Project_SWP391.Model.Bill", b =>
                {
                    b.Property<int>("BillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BillId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DeliveryId")
                        .HasColumnType("int");

                    b.Property<int>("DeliveryStatusDeliveryId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.Property<int>("TourId")
                        .HasColumnType("int");

                    b.Property<string>("UserFullName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BillId");

                    b.HasIndex("DeliveryStatusDeliveryId");

                    b.HasIndex("TourId");

                    b.ToTable("Bills");
                });

            modelBuilder.Entity("Project_SWP391.Model.BillDetail", b =>
                {
                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.Property<float>("ServicePrice")
                        .HasColumnType("real");

                    b.Property<DateTime>("TimeServiceUsed")
                        .HasColumnType("datetime2");

                    b.HasKey("BillId", "ServiceId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BillDetails");
                });

            modelBuilder.Entity("Project_SWP391.Model.DeliveryStatus", b =>
                {
                    b.Property<int>("DeliveryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("DeliveryId"));

                    b.Property<string>("DeliveryAddress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("DeliveryFee")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DeliveryStatusText")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("EstimatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("DeliveryId");

                    b.ToTable("DeliveryStatuses");
                });

            modelBuilder.Entity("Project_SWP391.Model.FarmImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<int>("KoiFarmFarmId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.HasIndex("KoiFarmFarmId");

                    b.ToTable("FarmImage");
                });

            modelBuilder.Entity("Project_SWP391.Model.Feedback", b =>
                {
                    b.Property<int>("FeedbackId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeedbackId"));

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Rating")
                        .HasColumnType("int");

                    b.HasKey("FeedbackId");

                    b.HasIndex("BillId")
                        .IsUnique();

                    b.ToTable("Feedbacks");
                });

            modelBuilder.Entity("Project_SWP391.Model.Koi", b =>
                {
                    b.Property<int>("KoiId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KoiId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FarmId")
                        .HasColumnType("int");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KoiFarmFarmId")
                        .HasColumnType("int");

                    b.Property<string>("KoiName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("KoiVarietyVarietyId")
                        .HasColumnType("int");

                    b.Property<float>("Length")
                        .HasColumnType("real");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateTime>("UpdateDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("VarietyId")
                        .HasColumnType("int");

                    b.Property<int>("YOB")
                        .HasColumnType("int");

                    b.HasKey("KoiId");

                    b.HasIndex("KoiFarmFarmId");

                    b.HasIndex("KoiVarietyVarietyId");

                    b.ToTable("Kois");
                });

            modelBuilder.Entity("Project_SWP391.Model.KoiBill", b =>
                {
                    b.Property<int>("KoiBillId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("KoiBillId"));

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<float>("DiscountPercent")
                        .HasColumnType("real");

                    b.Property<float>("FinalPrice")
                        .HasColumnType("real");

                    b.Property<int>("KoiId")
                        .HasColumnType("int");

                    b.Property<float>("OriginalPrice")
                        .HasColumnType("real");

                    b.HasKey("KoiBillId");

                    b.HasIndex("BillId");

                    b.HasIndex("KoiId");

                    b.ToTable("KoiBill");
                });

            modelBuilder.Entity("Project_SWP391.Model.KoiFarm", b =>
                {
                    b.Property<int>("FarmId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FarmId"));

                    b.Property<DateTime>("CloseHour")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FarmName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Hotline")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Introduction")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("OpenHour")
                        .HasColumnType("datetime2");

                    b.Property<float>("Rating")
                        .HasColumnType("real");

                    b.HasKey("FarmId");

                    b.ToTable("KoiFarms");
                });

            modelBuilder.Entity("Project_SWP391.Model.KoiImage", b =>
                {
                    b.Property<int>("ImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ImageId"));

                    b.Property<int>("KoiId")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ImageId");

                    b.HasIndex("KoiId");

                    b.ToTable("KoiImages");
                });

            modelBuilder.Entity("Project_SWP391.Model.KoiVariety", b =>
                {
                    b.Property<int>("VarietyId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VarietyId"));

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VarietyName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("VarietyId");

                    b.ToTable("KoiVarieties");
                });

            modelBuilder.Entity("Project_SWP391.Model.PayStatus", b =>
                {
                    b.Property<int>("PayId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PayId"));

                    b.Property<int>("BillId")
                        .HasColumnType("int");

                    b.Property<float>("Deposit")
                        .HasColumnType("real");

                    b.Property<float>("Remain")
                        .HasColumnType("real");

                    b.Property<bool>("Status")
                        .HasColumnType("bit");

                    b.HasKey("PayId");

                    b.HasIndex("BillId")
                        .IsUnique();

                    b.ToTable("PayStatuses");
                });

            modelBuilder.Entity("Project_SWP391.Model.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<string>("ServiceName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");
                });

            modelBuilder.Entity("Project_SWP391.Model.Tour", b =>
                {
                    b.Property<int>("TourId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TourId"));

                    b.Property<DateTime>("FinishTime")
                        .HasColumnType("datetime2");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("TourName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TourId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("Project_SWP391.Model.Bill", b =>
                {
                    b.HasOne("Project_SWP391.Model.DeliveryStatus", "DeliveryStatus")
                        .WithMany("Bills")
                        .HasForeignKey("DeliveryStatusDeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_SWP391.Model.Tour", "Tour")
                        .WithMany("Bills")
                        .HasForeignKey("TourId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeliveryStatus");

                    b.Navigation("Tour");
                });

            modelBuilder.Entity("Project_SWP391.Model.BillDetail", b =>
                {
                    b.HasOne("Project_SWP391.Model.Bill", "Bill")
                        .WithMany("BillDetails")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_SWP391.Model.Service", "Service")
                        .WithMany("BillDetails")
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Project_SWP391.Model.FarmImage", b =>
                {
                    b.HasOne("Project_SWP391.Model.KoiFarm", "KoiFarm")
                        .WithMany("FarmImages")
                        .HasForeignKey("KoiFarmFarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KoiFarm");
                });

            modelBuilder.Entity("Project_SWP391.Model.Feedback", b =>
                {
                    b.HasOne("Project_SWP391.Model.Bill", "Bill")
                        .WithOne("Feedback")
                        .HasForeignKey("Project_SWP391.Model.Feedback", "BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Project_SWP391.Model.Koi", b =>
                {
                    b.HasOne("Project_SWP391.Model.KoiFarm", "KoiFarm")
                        .WithMany("Kois")
                        .HasForeignKey("KoiFarmFarmId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_SWP391.Model.KoiVariety", "KoiVariety")
                        .WithMany("Kois")
                        .HasForeignKey("KoiVarietyVarietyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("KoiFarm");

                    b.Navigation("KoiVariety");
                });

            modelBuilder.Entity("Project_SWP391.Model.KoiBill", b =>
                {
                    b.HasOne("Project_SWP391.Model.Bill", "Bill")
                        .WithMany("KoiBills")
                        .HasForeignKey("BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Project_SWP391.Model.Koi", "Koi")
                        .WithMany()
                        .HasForeignKey("KoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");

                    b.Navigation("Koi");
                });

            modelBuilder.Entity("Project_SWP391.Model.KoiImage", b =>
                {
                    b.HasOne("Project_SWP391.Model.Koi", "Koi")
                        .WithMany("KoiImages")
                        .HasForeignKey("KoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Koi");
                });

            modelBuilder.Entity("Project_SWP391.Model.PayStatus", b =>
                {
                    b.HasOne("Project_SWP391.Model.Bill", "Bill")
                        .WithOne("PayStatus")
                        .HasForeignKey("Project_SWP391.Model.PayStatus", "BillId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Bill");
                });

            modelBuilder.Entity("Project_SWP391.Model.Bill", b =>
                {
                    b.Navigation("BillDetails");

                    b.Navigation("Feedback")
                        .IsRequired();

                    b.Navigation("KoiBills");

                    b.Navigation("PayStatus")
                        .IsRequired();
                });

            modelBuilder.Entity("Project_SWP391.Model.DeliveryStatus", b =>
                {
                    b.Navigation("Bills");
                });

            modelBuilder.Entity("Project_SWP391.Model.Koi", b =>
                {
                    b.Navigation("KoiImages");
                });

            modelBuilder.Entity("Project_SWP391.Model.KoiFarm", b =>
                {
                    b.Navigation("FarmImages");

                    b.Navigation("Kois");
                });

            modelBuilder.Entity("Project_SWP391.Model.KoiVariety", b =>
                {
                    b.Navigation("Kois");
                });

            modelBuilder.Entity("Project_SWP391.Model.Service", b =>
                {
                    b.Navigation("BillDetails");
                });

            modelBuilder.Entity("Project_SWP391.Model.Tour", b =>
                {
                    b.Navigation("Bills");
                });
#pragma warning restore 612, 618
        }
    }
}
